### ISSUE TITLE
List sensors by last date update

### ISSUE THREAD

**Issue by karimkawambwa** [opendata-stuttgart/feinstaub-map-v2#19]
<img width="398" alt="Screen Shot 2020-01-27 at 10 24 27 AM" src="https://user-images.githubusercontent.com/4308339/73156716-b407e880-40ef-11ea-9b2a-51d00597df74.png">
<img width="389" alt="Screen Shot 2020-01-27 at 10 24 09 AM" src="https://user-images.githubusercontent.com/4308339/73156718-b4a07f00-40ef-11ea-8cf3-23434fb5c908.png">

**Comment by ricki-z** [comment]
The sensors shown there have send data in the last 5 minutes.
For most users it is easier to find their sensor if the list is sorted by ID.

**Comment by karimkawambwa** [comment]
If thats the better used case for the users then sounds good.
