### ISSUE TITLE
Service dead? Or overload?

### ISSUE THREAD

**Issue by michapr** [opendata-stuttgart/feinstaub-map-v2#21]
Hi,

I get all the time only the map - without any data (or sensors).
What is wrong? I have ried different browsers (FireFox, Chrome)

Thanks,
Michael

**Comment by ricki-z** [comment]
We are working on this. As the traffic has increased massively in some data centers the internal networks are sometimes overloaded.
For the moment it seems like we could solve this for the registration page, but not for our main database.

**Comment by 23RoMax** [comment]
Is the service still affected?
Upon closer inspection, the requests to https://maps.sensor.community/data/v2/data.24h.json return a 200 but are empty.

**Comment by ricki-z** [comment]
Database crash. And as the data centers are a little bit overloaded at the moment the recovery needed much more time than usual.

**Comment by 23RoMax** [comment]
Maybe you guys could react to database crashes differently :) ?
Returning a 500 or better a 503 would indicate that the service is currently disrupted due to another service being disrupted. Maybe this helps people in their debugging efforts as well :)

**Comment by ricki-z** [comment]
We also had to disable the web services as otherwise the recreation would have needed much longer. So there wasn't a possibility to return a status code.
And just before someone is asking: Inserting a load balancer would result in a longer time a connection is open (while normal operation). This would result in more parallel connections. And this would result in other problems.

**Comment by michapr** [comment]
Hi,
about what number of parallel connections we are speaking here?
And what is the "normal" connection time for a process?
Thank you for your support!
Michael

**Comment by ricki-z** [comment]
The average:
11.500 sensors sending 2 measurements every 145 seconds: 158 new connections/second

But in reality this can go up to around 1000 parallel connections (i.e. all Raspi systems sending exactly every full minute, NTP synced ...)

Normal processing time is lower than 100 milliseconds. This depends also on the connection speed (TCP handshake, TLS handshake if enabled).

**Comment by 23RoMax** [comment]
> We also had to disable the web services as otherwise the recreation would have needed much longer. So there wasn't a possibility to return a status code.
> And just before someone is asking: Inserting a load balancer would result in a longer time a connection is open (while normal operation). This would result in more parallel connections. And this would result in other problems.

Got it! Thank you for the clarification and efforts!
Cheers,

Max
