### ISSUE TITLE
Show translated page

### ISSUE THREAD

**Issue by Petarkir2000** [opendata-stuttgart/feinstaub-map-v2#26]
Is it possible to display the translation of the map not only on recognition of the browser/system language, but also based on a map language selection - drop-down menu or other. Many users have language browser settings other than their primary language.

**Comment by ricki-z** [comment]
Yes, it's possible. But someone has to write the code for this ;-).
We will add this to the 'features wanted' list.

**Comment by ricki-z** [comment]
And as comment: If a user is using a browser language other than their own, then they should understand this other language. Or how will they use the browser menus if they don't understand them ...?

**Comment by Petarkir2000** [comment]
I would agree with your comment, but regardless of understanding one language, it is different to be written / displayed in your native language. We all understand English here, but it's another thing to read in German, isn't it? :)

**Comment by ricki-z** [comment]
That's true. I will check this. I thought Englisch is the default.

**Comment by ricki-z** [comment]
I have checked this (prio Spanish, German, English). The result was a map with english texts.
So if the first configured language isn't found then English is shown.
And I would configure other languages in a way that my own is the default and other languages have a lower priority.

**Comment by Petarkir2000** [comment]
Now it work as is required! Thank you!
